### ISSUE TITLE
Newest push breaks the appveyor Windows build

### ISSUE THREAD

**Issue by darki2002** [AMOS-ss16-proj3/amos-ss16-proj3#21]
The newest commits / merge broke the windows build.
Appveyor errors:

> c:\projects\wiresharkBuild\plugins\doip\doip.vcxproj"
> 
> (default target) (1) ->
>       (Link target) -> 
>         packet-doip.obj : error LNK2019: unresolved external symbol new_create_dissector_handle >referenced in function proto_reg_handoff_doip [c:\projects\wiresharkBuild\plugins\doip\doip.vcxproj]
>         C:\projects\wiresharkBuild\run\RelWithDebInfo\plugins\doip.dll : fatal error LNK1120: 1 unresolved >externals [c:\projects\wiresharkBuild\plugins\doip\doip.vcxproj]
> 
>   66 Warning(s)
>   2 Error(s)

**Comment by darki2002** [comment]
new_create_dissector_handle (of epan/packet.c) not available any more in the latest wireshark version 2.0.4

**Comment by dustywind** [comment]
#define VERSION_MAJOR 1
aus config.h
moeglicher ansatz:
ifdef VERSION_MAJOR == 1
new_dissector_handle
else
dissector_handle
endif

**Comment by darki2002** [comment]
Ifdef ok and working, because:
In the old Wireshark version 1, the dissector_t has another format than in the ws 2.0.4 (or even other ws 2 versions).
Old:
`typedef int (*dissector_t)(tvbuff_t *, packet_info *, proto_tree *);
typedef int (*new_dissector_t)(tvbuff_t *, packet_info *, proto_tree *, void *);`

New:
`typedef int (*dissector_t)(tvbuff_t *, packet_info *, proto_tree *, void *);`

Maybe we should not split it in wireshark v1 and v2 but instead search the exact point when new_dissector_t was merged into dissector_t

**Comment by darki2002** [comment]
Change commit in Wireshark repository (11 Dec 2015):
[Wireshark commit 99028789cbf3f0e6193d6158ff9e0e3b11b2c505](https://github.com/wireshark/wireshark/commit/99028789cbf3f0e6193d6158ff9e0e3b11b2c505)

**Comment by darki2002** [comment]
This problem seems to be fixed some days ago - closed -
